# Generated by Django 3.1.3 on 2020-11-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('rating', models.PositiveIntegerField(default=2)),
            ],
            options={
                'verbose_name_plural': 'shops',
            },
        ),
    ]
